version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-service
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
    depends_on:
      - web-app
    networks:
      - main_network

  web-app:
    image: kartychak/hillel-django-project:0.1.0
    container_name: web-app
    restart: on-failure
    platform: linux/amd64
    healthcheck:
      test: curl -f http://localhost:8000/admin/ || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    env_file: ./.env
    depends_on:
      - postgres_database
    command: sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 shop.wsgi:application --reload -w 4 --log-level info"

    networks:
      - main_network

  postgres_database:
    image: postgres:15
    container_name: postgres_database
    restart: always
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=de_user
      - POSTGRES_PASSWORD=db_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-entrypoint:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]  # pg_isready - is a postgres util
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - main_network

  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./redis_data:/data   #  redis side we can see by command "CONFIG get dir" in cli
    command: [ "redis-server", "--appendonly", "no", "--maxmemory", "100mb", "--maxmemory-policy", "allkeys-lru" ]
    healthcheck:
      test: ['CMD', "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - main_network

networks:
  main_network:
    driver: bridge

volumes:
  static_volume:
  postgres-data:
